- hosts: all
  sudo: yes
  user: ubuntu
  vars:
      ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install required packages
      apt: name={{ item }} update_cache=yes state=latest
      sudo: yes
      with_items:
        - nginx
        - git

        - python3-mysqldb
        - mysql-server

        - python3-pip

    - name: Update apt cache
      apt: update_cache=yes

    - name: upgrade pip
      pip:
        name:  "{{ item }}"
        executable: pip3
      with_items:
        - "--upgrade pip"

#    - name: Stop MySQL
#      service: name=mysql state=stopped
#
#    - name: set environment variables
#      shell: systemctl set-environment MYSQLD_OPTS="--skip-grant-tables"
#
#    - name: Start MySQL
#      service: name=mysql state=started
#
#    - name: sql query
#      command:  mysql -u root --execute="UPDATE mysql.user SET authentication_string = PASSWORD('root') WHERE User = 'root' AND Host = '0.0.0.0';"
#
#    - name: sql query flush
#      command:  mysql -u root --execute="FLUSH PRIVILEGES"
#
#    - name: Stop MySQL
#      service: name=mysql state=stopped
#
#    - name: unset environment variables
#      shell: systemctl unset-environment MYSQLD_OPTS
#
#    - name: Start MySQL
#      service: name=mysql state=started

#    - name: Create admin user for mysql
#      mysql_user:
#        user: "admin"
#        password: "admin"
#        priv: "*.*:ALL,GRANT"
#        state: present
#
    - name: Set a new root password
      mysql_user: check_implicit_admin=yes
                  login_user=root
                  user=root
                  password='root'
                  host={{ item }}
                  priv='*.*:ALL,GRANT'
      with_items:
        - localhost
      notify:
          - restart_mysql

    - name: Set mysql config
      mysql_db:
        login_host: "localhost"
        name: card_game

  handlers:
    - name: restart_mysql
      service: name=mysql
               state=restarted